In [1]:
from d_load import d_load

bt, at = d_load.d_load()

In [2]:
bt

,update_id,best_bid_price,best_bid_qty,best_ask_price,best_ask_qty,transaction_time,event_time
0,4264349177374,64020.3,1.790,64020.4,3.636,1711238400018,1711238400024
1,4264349179250,64020.3,1.790,64020.4,3.634,1711238400033,1711238400039
2,4264349179655,64020.3,1.790,64020.4,3.640,1711238400037,1711238400044
3,4264349181766,64020.3,2.002,64020.4,3.640,1711238400049,1711238400058
4,4264349184343,64020.3,2.052,64020.4,3.640,1711238400064,1711238400073
...,...,...,...,...,...,...,...
91449742,4312569098807,69642.0,0.660,69642.1,3.074,1711843199631,1711843199637
91449743,4312569103997,69642.0,0.660,69642.1,3.071,1711843199735,1711843199741
91449744,4312569105328,69642.0,0.660,69642.1,3.074,1711843199775,1711843199780
91449745,4312569109173,69642.0,0.660,69642.1,3.076,1711843199878,1711843199885
91449746,4312569112552,69642.0,0.660,69642.1,3.078,1711843199980,1711843199987

In [3]:
at

,agg_trade_id,price,quantity,first_trade_id,last_trade_id,transact_time,is_buyer_maker
0,2096641851,64020.4,3.194,4790419953,4790419970,1711238400088,False
1,2096641852,64021.2,0.003,4790419971,4790419971,1711238400094,False
2,2096641853,64022.0,0.002,4790419972,4790419972,1711238400094,False
3,2096641854,64022.2,0.004,4790419973,4790419973,1711238400094,False
4,2096641855,64023.8,0.004,4790419974,4790419974,1711238400095,False
...,...,...,...,...,...,...,...
10893227,2107535078,69642.2,0.009,4817720262,4817720262,1711843198883,True
10893228,2107535079,69642.1,0.258,4817720263,4817720263,1711843198883,True
10893229,2107535080,69642.0,0.238,4817720264,4817720265,1711843198883,True
10893230,2107535081,69642.1,0.220,4817720266,4817720267,1711843198941,False
10893231,2107535082,69642.1,0.556,4817720268,4817720274,1711843199082,False